import { createFileRoute, Link } from "@tanstack/react-router";
import { Check, MapPin, MessageSquareText, ScanSearch } from "lucide-react";
import { Button } from "@/components/ui/button";
import { pick, useLanguage } from "@/lib/i18n";
import storeInterior from "@/assets/store-interior.jpg";

export const Route = createFileRoute("/about")({
  head: () => ({ meta: [{ title: "O nas — Auto Parts Store in Maldyty" }, { name: "description", content: "Poznaj lokalny sklep motoryzacyjny Auto Parts Store in Maldyty przy ul. Prusa 5." }, { property: "og:title", content: "O nas — Auto Parts Store in Maldyty" }, { property: "og:description", content: "Lokalne wsparcie w doborze części samochodowych w Małdytach." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: AboutPage,
});

function AboutPage() { const { language } = useLanguage(); return <>
  <section className="page-wrap page-section grid items-center gap-10 lg:grid-cols-2"><div><p className="eyebrow">{pick(language, { pl: "O nas", en: "About us" })}</p><h1 className="mt-3 text-4xl font-semibold leading-tight sm:text-5xl">{pick(language, { pl: "Lokalna wiedza. Trafny dobór.", en: "Local knowledge. Accurate matching." })}</h1><p className="mt-5 max-w-xl text-lg leading-relaxed text-muted-foreground">{pick(language, { pl: "Auto Parts Store in Maldyty to punkt dla kierowców i warsztatów szukających właściwych części bez niepotrzebnego czekania.", en: "Auto Parts Store in Maldyty helps drivers and workshops find the right parts without unnecessary waiting." })}</p><p className="mt-4 max-w-xl leading-relaxed text-muted-foreground">{pick(language, { pl: "Łączymy praktyczne doradztwo z szerokim dostępem do części wielu producentów. Rozmawiamy po polsku i angielsku.", en: "We combine practical advice with broad access to parts from many manufacturers. We speak Polish and English." })}</p></div><div className="image-frame"><img src={storeInterior} alt="Store interior" width={1280} height={960} className="aspect-[4/3] w-full object-cover" /></div></section>
  <section className="border-y border-foreground/10 bg-surface/30"><div className="page-wrap page-section"><p className="eyebrow">{pick(language, { pl: "Jak pomagamy", en: "How we help" })}</p><div className="mt-7 grid gap-4 md:grid-cols-3">{[[ScanSearch,"Dobieramy po VIN","Match by VIN","Sprawdzamy wersję silnika i właściwy numer części.","We check the engine version and correct part number."],[MessageSquareText,"Mówimy jasno","Clear advice","Wyjaśniamy różnice między wariantami i producentami.","We explain differences between variants and brands."],[MapPin,"Jesteśmy na miejscu","We are local","Możesz obejrzeć produkt i odebrać go w Małdytach.","Inspect and collect your part locally in Małdyty."]].map(([Icon,pl,en,plD,enD]) => { const Comp = Icon as typeof Check; return <article key={String(pl)} className="glass-panel p-6"><Comp className="text-primary" /><h2 className="mt-5 text-xl font-semibold">{language === "pl" ? String(pl) : String(en)}</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{language === "pl" ? String(plD) : String(enD)}</p></article>; })}</div></div></section>
  <section className="page-wrap page-section flex flex-col items-start justify-between gap-5 md:flex-row md:items-center"><div><h2 className="text-3xl font-semibold">{pick(language, { pl: "Odwiedź nas w Małdytach", en: "Visit us in Małdyty" })}</h2><p className="mt-2 text-muted-foreground">ul. Prusa 5, 14-330 Małdyty</p></div><Button variant="dark" asChild><Link to="/find-us">{pick(language, { pl: "Mapa i kontakt", en: "Map and contact" })}</Link></Button></section>
  </>; }